export { Microsoft } from "./microsoft";
export { Decathlon } from "./decathlon";
export { Facebook } from "./facebook";
export { TokStok } from "./tokStok";
export { Indigo } from "./indigo";
export { Unimed } from "./unimed";
export { Google } from "./google";
export { Apple } from "./apple";
export { Nba } from "./nba";
