import { InitialStateProps } from "../types";

export const COLORS = [
  {
    name: "Laranja",
    ref: "orange",
    primary_hex: "#FB923C",
    secondary_hex: "#FDBA74",
    primary_color: "bg-orange-500",
    border_color: "border-orange-500",
    secondary_color: "bg-orange-200",
    primary_font: "text-orange-500",
    gradient: "bg-gradient-to-br from-[#FDBA74] via-[#FEF3C7] to-[#FFF7ED]",
  },
  {
    name: "Vermelho",
    ref: "red",
    primary_hex: "#EF4444",
    secondary_hex: "#FCA5A5",
    primary_color: "bg-red-500",
    border_color: "border-red-500",
    secondary_color: "bg-red-200",
    primary_font: "text-red-500",
    gradient: "bg-gradient-to-tr from-[#FEF2F2] via-[#FEE2E2] to-[#fff]",
  },
  {
    name: "Cereja",
    ref: "rose",
    primary_hex: "#F43F5E",
    secondary_hex: "#FDA4AF",
    primary_color: "bg-rose-500",
    border_color: "border-rose-500",
    secondary_color: "bg-rose-200",
    primary_font: "text-rose-500",
    gradient: "bg-gradient-to-tr from-[#FFF1F2] via-[#FFE4E6] to-[#fff]",
  },
  {
    name: "Rosa",
    ref: "pink",
    primary_hex: "#EC4899",
    secondary_hex: "#F9A8D4",
    primary_color: "bg-pink-500",
    border_color: "border-pink-500",
    secondary_color: "bg-pink-200",
    primary_font: "text-pink-500",
    gradient: "bg-gradient-to-tr from-[#FDF2F8] via-[#FCE7F3] to-[#fff]",
  },
  {
    name: "Magenta",
    ref: "fuschia",
    primary_hex: "#D946EF",
    secondary_hex: "#F0ABFC",
    primary_color: "bg-fuschia-500",
    border_color: "border-fuschia-500",
    secondary_color: "bg-fuschia-200",
    primary_font: "text-fuschia-500",
    gradient: "bg-gradient-to-tr from-[#FDF4FF] via-[#FAE8FF] to-[#fff]",
  },
  {
    name: "Violeta",
    ref: "violet",
    primary_hex: "#8B5CF6",
    secondary_hex: "#A78BFA",
    primary_color: "bg-violet-500",
    border_color: "border-violet-500",
    secondary_color: "bg-violet-200",
    primary_font: "text-violet-500",
    gradient: "bg-gradient-to-tr from-[#F5F3FF] via-[#EDE9FE] to-[#fff]",
  },
  {
    name: "Indigo",
    ref: "indigo",
    primary_hex: "#6366F1",
    secondary_hex: "#A5B4FC",
    primary_color: "bg-indigo-500",
    border_color: "border-indigo-500",
    secondary_color: "bg-indigo-200",
    primary_font: "text-indigo-500",
    gradient: "bg-gradient-to-tr from-[#EEF2FF] via-[#E0E7FF] to-[#fff]",
  },
  {
    name: "Azul",
    ref: "blue",
    primary_hex: "#3B82F6",
    secondary_hex: "#93C5FD",
    primary_color: "bg-blue-500",
    border_color: "border-blue-500",
    secondary_color: "bg-blue-200",
    primary_font: "text-blue-500",
    gradient: "bg-gradient-to-tr from-[#EFF6FF] via-[#DBEAFE] to-[#fff]",
  },
  {
    name: "Céu",
    ref: "sky",
    primary_hex: "#0EA5E9",
    secondary_hex: "#7DD3FC",
    primary_color: "bg-sky-500",
    border_color: "border-sky-500",
    secondary_color: "bg-sky-200",
    primary_font: "text-sky-500",
    gradient: "bg-gradient-to-tr from-[#EFF6FF] via-[#DBEAFE] to-[#fff]",
  },
  {
    name: "Ciano",
    ref: "cyan",
    primary_hex: "#06B6D4",
    secondary_hex: "#67E8F9",
    primary_color: "bg-cyan-500",
    border_color: "border-cyan-500",
    secondary_color: "bg-cyan-200",
    primary_font: "text-cyan-500",
    gradient: "bg-gradient-to-tr from-[#ECFEFF] via-[#CFFAFE] to-[#fff]",
  },
  {
    name: "Turquesa",
    ref: "teal",
    primary_hex: "#14B8A6",
    secondary_hex: "#5EEAD4",
    primary_color: "bg-teal-500",
    border_color: "border-teal-500",
    secondary_color: "bg-teal-200",
    primary_font: "text-teal-500",
    gradient: "bg-gradient-to-tr from-[#F0FDFA] via-[#CCFBF1] to-[#fff]",
  },
  {
    name: "Esmeralda",
    ref: "esmerald",
    primary_hex: "#10B981",
    secondary_hex: "#6EE7B7",
    primary_color: "bg-esmerald-500",
    border_color: "border-esmerald-500",
    secondary_color: "bg-esmerald-200",
    primary_font: "text-esmerald-500",
    gradient: "bg-gradient-to-tr from-[#ECFDF5] via-[#D1FAE5] to-[#fff]",
  },
  {
    name: "Verde",
    ref: "green",
    primary_hex: "#22C55E",
    secondary_hex: "#86EFAC",
    primary_color: "bg-green-500",
    border_color: "border-green-500",
    secondary_color: "bg-green-200",
    primary_font: "text-green-500",
    gradient: "bg-gradient-to-tr from-[#F0FDF4] via-[#DCFCE7] to-[#fff]",
  },
  {
    name: "Lima",
    ref: "lime",
    primary_hex: "#65A30D",
    secondary_hex: "#BEF264",
    primary_color: "bg-lime-500",
    border_color: "border-lime-500",
    secondary_color: "bg-lime-200",
    primary_font: "text-lime-500",
    gradient: "bg-gradient-to-tr from-[#F7FEE7] via-[#ECFCCB] to-[#fff]",
  },
  {
    name: "Amarelo",
    ref: "amber",
    primary_hex: "#F59E0B",
    secondary_hex: "#FCD34D",
    primary_color: "bg-amber-500",
    border_color: "border-amber-500",
    secondary_color: "bg-amber-200",
    primary_font: "text-amber-500",
    gradient: "bg-gradient-to-tr from-[#FFFBEB] via-[#FEF3C7] to-[#fff]",
  },
  {
    name: "Marrom",
    ref: "amber",
    primary_hex: "#78350F",
    secondary_hex: "#C1A391",
    primary_color: "bg-amber-900",
    border_color: "border-amber-900",
    secondary_color: "bg-amber-100",
    primary_font: "text-amber-900",
    gradient: "bg-gradient-to-tr from-[#C1A391] via-[#F1ECE8] to-[#fff]",
  },
  {
    name: "Preto",
    ref: "slate",
    primary_hex: "#020617",
    secondary_hex: "#404040",
    primary_color: "bg-slate-950",
    border_color: "border-slate-950",
    secondary_color: "bg-slate-600",
    primary_font: "text-slate-950",
    gradient: "bg-gradient-to-tr from-[#F5F5F5] via-[#D4D4D4] to-[#fff]",
  },
  {
    name: "Cinza",
    ref: "slate",
    primary_hex: "#64748B",
    secondary_hex: "#CBD5E1",
    primary_color: "bg-slate-500",
    border_color: "border-slate-500",
    secondary_color: "bg-slate-400",
    primary_font: "text-slate-500",
    gradient: "bg-gradient-to-tr from-[#FAFAFA] via-[#F5F5F5] to-[#fff]",
  },
];

export const SEGMENTS = [
  "Tecnologia & Software",
  "Gestão",
  "Marketing",
  "Vendas",
  "Recrutamento & Seleção",
  "Saude",
  "Educação",
  "Outros",
];

export const ROLES = [
  "Assistente",
  "Analista / Especialista",
  "Coordenador",
  "Gerente",
  "Diretor / C-level",
  "Proprietário / Sócio",
  "Outros",
];

export const DEPARTMENTS = [
  "💻 TI",
  "🪴 Recursos Humanos",
  "💰 Financeiro",
  "🛟 CS & Suporte",
  "📢 Marketing",
  "💼 Vendas",
  "📦 Compras",
  "⚙️ Administração",
  "⚖️ Jurídico",
  "🛠️ Operações / Serviços",
  "💡Desenvolvimento (P&D)",
];

export const SIZE = [
  "1 a 5",
  "6 a 10",
  "11 a 50",
  "51 a 200",
  "201 a 500",
  "mais de 500",
];

export const FONTS = [
  "Youtube",
  "Linkedin",
  "Amigo / Colega",
  "Facebook / Instagram",
  "Evento / Webinar",
  "Mecanismo de busca (Google, Bing, etc.)",
  "Outro",
];

export const initialState: InitialStateProps = {
  email: null,
  password: null,
  fullName: null,
  phoneNumber: null,
  role: null,
  fromWhere: null,
  companyName: null,
  companyField: null,
  companySize: null,
  department: null,
  url: null,
  color: "",
  step: 1,
};
